# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7210cceb6f47c3b415671e8918790c631a1ce1391529bd6088360ec1841a13c2f8a0b6441e96183642e17495cf6d8fea9a2251033a74ea3fc46b689251d703a7

test:
  secret_key_base: 6dabd1b2da93dedb2a4c8d29bfc6cb067f2dda0172c9bfcc48c253a3c0e2b0c3bdf6c6a902f03f258f3d433075d402468f6cd8a68373b92477cf2ff35cf3f674

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
